$(document).ready(function(){

	Grid.IsCheckBoxRequired = true;

	Grid.GridData.rows = [
   [
      {
         "col":"col1",
         "value":"row1col1"
      },
      {
         "col":"col2",
         "value":"row1col1"
      },
      {
         "col":"col3",
         "value":"row1col3"
      },
      {
         "col":"col4",
         "value":"row1col4"
      },
      {
         "col":"col5",
         "value":"row1col5"
      },
      {
         "col":"col6",
         "value":"row1col6"
      },
      {
         "col":"col7",
         "value":"row1col7"
      }
   ],
   [
      {
         "col":"col1",
         "value":"row2col1"
      },
      {
         "col":"col2",
         "value":"row2col1"
      },
      {
         "col":"col3",
         "value":"row2col3"
      },
      {
         "col":"col4",
         "value":"row2col4"
      },
      {
         "col":"col5",
         "value":"row2col5"
      },
      {
         "col":"col6",
         "value":"row2col6"
      },
      {
         "col":"col7",
         "value":"row2col7"
      }
   ],
   [
      {
         "col":"col1",
         "value":"row3col1"
      },
      {
         "col":"col2",
         "value":"row3col1"
      },
      {
         "col":"col3",
         "value":"row3col3"
      },
      {
         "col":"col4",
         "value":"row3col4"
      },
      {
         "col":"col5",
         "value":"row3col5"
      },
      {
         "col":"col6",
         "value":"row3col6"
      },
      {
         "col":"col7",
         "value":"row3col7"
      }
   ],
   [
      {
         "col":"col1",
         "value":"row4col1"
      },
      {
         "col":"col2",
         "value":"row4col1"
      },
      {
         "col":"col3",
         "value":"row4col3"
      },
      {
         "col":"col4",
         "value":"row4col4"
      },
      {
         "col":"col5",
         "value":"row4col5"
      },
      {
         "col":"col6",
         "value":"row4col6"
      },
      {
         "col":"col7",
         "value":"row4col7"
      }
   ],
   [
      {
         "col":"col1",
         "value":"row5col1"
      },
      {
         "col":"col2",
         "value":"row5col1"
      },
      {
         "col":"col3",
         "value":"row5col3"
      },
      {
         "col":"col4",
         "value":"row5col4"
      },
      {
         "col":"col5",
         "value":"row5col5"
      },
      {
         "col":"col6",
         "value":"row5col6"
      },
      {
         "col":"col7",
         "value":"row5col7"
      }
   ],
   [
      {
         "col":"col1",
         "value":"row6col1"
      },
      {
         "col":"col2",
         "value":"row6col1"
      },
      {
         "col":"col3",
         "value":"row6col3"
      },
      {
         "col":"col4",
         "value":"row6col4"
      },
      {
         "col":"col5",
         "value":"row6col5"
      },
      {
         "col":"col6",
         "value":"row6col6"
      },
      {
         "col":"col7",
         "value":"row6col7"
      }
   ],
   [
      {
         "col":"col1",
         "value":"row7col1"
      },
      {
         "col":"col2",
         "value":"row7col1"
      },
      {
         "col":"col3",
         "value":"row7col3"
      },
      {
         "col":"col4",
         "value":"row7col4"
      },
      {
         "col":"col5",
         "value":"row7col5"
      },
      {
         "col":"col6",
         "value":"row7col6"
      },
      {
         "col":"col7",
         "value":"row7col7"
      }
   ],
   [
      {
         "col":"col1",
         "value":"row8col1"
      },
      {
         "col":"col2",
         "value":"row8col1"
      },
      {
         "col":"col3",
         "value":"row8col3"
      },
      {
         "col":"col4",
         "value":"row8col4"
      },
      {
         "col":"col5",
         "value":"row8col5"
      },
      {
         "col":"col6",
         "value":"row8col6"
      },
      {
         "col":"col7",
         "value":"row8col7"
      }
   ],
   [
      {
         "col":"col1",
         "value":"row9col1"
      },
      {
         "col":"col2",
         "value":"row9ol1"
      },
      {
         "col":"col3",
         "value":"row9col3"
      },
      {
         "col":"col4",
         "value":"row9col4"
      },
      {
         "col":"col5",
         "value":"row9col5"
      },
      {
         "col":"col6",
         "value":"row9col6"
      },
      {
         "col":"col7",
         "value":"row9col7"
      }
   ],
   [
      {
         "col":"col1",
         "value":"row10col1"
      },
      {
         "col":"col2",
         "value":"row10col1"
      },
      {
         "col":"col3",
         "value":"row10col3"
      },
      {
         "col":"col4",
         "value":"row10col4"
      },
      {
         "col":"col5",
         "value":"row10col5"
      },
      {
         "col":"col6",
         "value":"row10col6"
      },
      {
         "col":"col7",
         "value":"row10col7"
      }
   ],
   [
      {
         "col":"col1",
         "value":"row11col1"
      },
      {
         "col":"col2",
         "value":"row11col1"
      },
      {
         "col":"col3",
         "value":"ro11col3"
      },
      {
         "col":"col4",
         "value":"row11col4"
      },
      {
         "col":"col5",
         "value":"row11col5"
      },
      {
         "col":"col6",
         "value":"ro11col6"
      },
      {
         "col":"col7",
         "value":"row11col7"
      }
   ],
   [
      {
         "col":"col1",
         "value":"row12col1"
      },
      {
         "col":"col2",
         "value":"row12col1"
      },
      {
         "col":"col3",
         "value":"row12col3"
      },
      {
         "col":"col4",
         "value":"row12col4"
      },
      {
         "col":"col5",
         "value":"row12col5"
      },
      {
         "col":"col6",
         "value":"row12col6"
      },
      {
         "col":"col7",
         "value":"row12col7"
      }
   ],
   [
      {
         "col":"col1",
         "value":"row7col1"
      },
      {
         "col":"col2",
         "value":"row7col1"
      },
      {
         "col":"col3",
         "value":"row7col3"
      },
      {
         "col":"col4",
         "value":"row7col4"
      },
      {
         "col":"col5",
         "value":"row7col5"
      },
      {
         "col":"col6",
         "value":"row7col6"
      },
      {
         "col":"col7",
         "value":"row7col7"
      }
   ],
   [
      {
         "col":"col1",
         "value":"row7col1"
      },
      {
         "col":"col2",
         "value":"row7col1"
      },
      {
         "col":"col3",
         "value":"row7col3"
      },
      {
         "col":"col4",
         "value":"row7col4"
      },
      {
         "col":"col5",
         "value":"row7col5"
      },
      {
         "col":"col6",
         "value":"row7col6"
      },
      {
         "col":"col7",
         "value":"row7col7"
      }
   ],
   [
      {
         "col":"col1",
         "value":"row7col1"
      },
      {
         "col":"col2",
         "value":"row7col1"
      },
      {
         "col":"col3",
         "value":"row7col3"
      },
      {
         "col":"col4",
         "value":"row7col4"
      },
      {
         "col":"col5",
         "value":"row7col5"
      },
      {
         "col":"col6",
         "value":"row7col6"
      },
      {
         "col":"col7",
         "value":"row7col7"
      }
   ],
   [
      {
         "col":"col1",
         "value":"row7col1"
      },
      {
         "col":"col2",
         "value":"row7col1"
      },
      {
         "col":"col3",
         "value":"row7col3"
      },
      {
         "col":"col4",
         "value":"row7col4"
      },
      {
         "col":"col5",
         "value":"row7col5"
      },
      {
         "col":"col6",
         "value":"row7col6"
      },
      {
         "col":"col7",
         "value":"row7col7"
      }
   ],
   [
      {
         "col":"col1",
         "value":"row7col1"
      },
      {
         "col":"col2",
         "value":"row7col1"
      },
      {
         "col":"col3",
         "value":"row7col3"
      },
      {
         "col":"col4",
         "value":"row7col4"
      },
      {
         "col":"col5",
         "value":"row7col5"
      },
      {
         "col":"col6",
         "value":"row7col6"
      },
      {
         "col":"col7",
         "value":"row7col7"
      }
   ],
   [
      {
         "col":"col1",
         "value":"row7col1"
      },
      {
         "col":"col2",
         "value":"row7col1"
      },
      {
         "col":"col3",
         "value":"row7col3"
      },
      {
         "col":"col4",
         "value":"row7col4"
      },
      {
         "col":"col5",
         "value":"row7col5"
      },
      {
         "col":"col6",
         "value":"row7col6"
      },
      {
         "col":"col7",
         "value":"row7col7"
      }
   ]
];
	Grid.BindGrid('divGrid');
});
